name: 功能建议
description: 描述观看流程中遇到的问题
body:
  - type: textarea
    id: problem
    attributes:
      label: 当前要完成什么，以及哪里受阻
    validations:
      required: true
  - type: textarea
    id: outcome
    attributes:
      label: 期望的行为与可接受的替代方式
    validations:
      required: true
