import type { LocalResourceCatalog } from "../types";

export const catalog: LocalResourceCatalog = {
  schemaVersion: 1,
  productId: "siaovplay",
  updatedAt: "2026-08-08",
  packageProfile: "app-only",
  bundlePolicy: {
    maximumExceptionBytes: 20_000_000,
    allowlistedResourceIds: [],
  },
  capabilities: [
    {
      id: "basic_media",
      title: "基础视频支持",
      resourceIds: ["ffmpeg-cpu"],
      profileIds: [],
      requiresCapabilityIds: [],
    },
    {
      id: "url_import",
      title: "在线视频导入",
      resourceIds: ["ffmpeg-cpu", "yt-dlp"],
      profileIds: [],
      requiresCapabilityIds: [],
    },
    {
      id: "local_transcription",
      title: "本地字幕识别",
      resourceIds: ["ffmpeg-cpu", "whisper-cpu"],
      profileIds: ["fast", "standard"],
      requiresCapabilityIds: [],
    },
  ],
  profiles: [
    {
      id: "fast",
      title: "快速",
      resourceIds: ["whisper-model-base"],
      recommended: false,
    },
    {
      id: "standard",
      title: "标准",
      resourceIds: ["whisper-model-small"],
      recommended: true,
    },
  ],
  resources: [
    {
      ...{ installedSize: null, expectedDownloadSize: null, artifact: null, entrypoints: {}, sourceCommit: null, patchSha256: null, requires: null, distribution: null },
      id: "ffmpeg-cpu",
      version: "8.1.2-34-g9b6c8969e0",
      platform: "windows-x86_64",
      kind: "archive",
      bundled: false,
      installedSize: 175_929_962,
      license: "LGPL-2.1-or-later",
      sourcePage: "https://example.com/ffmpeg",
      artifact: {
        stripComponents: null,
        url: "https://example.com/ffmpeg.zip",
        size: 70_508_781,
        sha256: "a".repeat(64),
        format: "zip",
      },
      entrypoints: {},
      healthCheck: "ffmpeg-version",
    },
    {
      ...{ installedSize: null, expectedDownloadSize: null, artifact: null, entrypoints: {}, sourceCommit: null, patchSha256: null, requires: null, distribution: null },
      id: "yt-dlp",
      version: "2026.08.19",
      platform: "windows-x86_64",
      kind: "file",
      bundled: false,
      installedSize: 17_840_399,
      license: "GPL-3.0-or-later",
      sourcePage: "https://example.com/yt-dlp",
      artifact: {
        stripComponents: null,
        url: "https://example.com/yt-dlp.exe",
        size: 17_840_399,
        sha256: "b".repeat(64),
        format: "file",
      },
      entrypoints: {},
      healthCheck: "yt-dlp-version",
    },
    {
      ...{ installedSize: null, expectedDownloadSize: null, artifact: null, entrypoints: {}, sourceCommit: null, patchSha256: null, requires: null, distribution: null },
      id: "whisper-cpu",
      version: "1.9.1",
      platform: "windows-x86_64",
      kind: "archive",
      bundled: false,
      installedSize: 20_355_072,
      license: "MIT",
      sourcePage: "https://example.com/recognition-runtime",
      artifact: {
        url: "https://example.com/whisper-bin-x64.zip",
        size: 7_982_101,
        sha256: "f".repeat(64),
        format: "zip",
        stripComponents: 1,
      },
      entrypoints: { whisperCli: "whisper-cli.exe" },
      healthCheck: "whisper-cli-version",
    },
    {
      ...{ installedSize: null, expectedDownloadSize: null, artifact: null, entrypoints: {}, sourceCommit: null, patchSha256: null, requires: null, distribution: null },
      id: "whisper-model-base",
      version: "base",
      platform: "all",
      kind: "model",
      bundled: false,
      installedSize: 147_951_465,
      license: "MIT",
      sourcePage: "https://example.com/recognition-model-base",
      artifact: {
        stripComponents: null,
        url: "https://example.com/base.bin",
        size: 147_951_465,
        sha256: "e".repeat(64),
        format: "file",
      },
      entrypoints: { model: "base.bin" },
      healthCheck: "sha256",
    },
    {
      ...{ installedSize: null, expectedDownloadSize: null, artifact: null, entrypoints: {}, sourceCommit: null, patchSha256: null, requires: null, distribution: null },
      id: "whisper-model-small",
      version: "small",
      platform: "all",
      kind: "model",
      bundled: false,
      installedSize: 487_601_967,
      license: "MIT",
      sourcePage: "https://example.com/recognition-model",
      artifact: {
        stripComponents: null,
        url: "https://example.com/model.bin",
        size: 487_601_967,
        sha256: "c".repeat(64),
        format: "file",
      },
      entrypoints: {},
      healthCheck: "sha256",
    },
  ],
};
